<?php
$helper = $this->helper('Abhay\CustomerAge\Helper\Data');
$enable=$helper->isEnabled();
$age=$helper->isAge();
if($enable)
{
  echo '<div class="Age field required">
            <label class="label" for="age">
                <span>Age</span>
            </label>
            <div class="control">
                <input type="text"
                       name="age"
                       id="age"
                       class="input-text"
                       data-validate="{required:true}">
            </div>
        </div>';
}
?>
